### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jnthn18/project10#1]
This is looking very good. There's just one tweak I'd like you to make. When I enter a blank location, I'm getting this message twice: `Please enter the location of show as city, state`. That's because `validates_format_of` will automatically check to make sure a field isn't blank (unless that would match the regex). To fix this, you can simply delete [this line](https://github.com/jnthn18/project10/blob/master/app/models/music_show.rb#L4).

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by jnthn18** [comment]
Should be fixed now!

**Comment by chrisvfritz** [comment]
:+1: Looks great!
